module.exports = {
    lightAlgorithm: {
        colorPrimary: '#006fff',
        colorText: '#000000',
        colorTextQuaternary: '#000000',
        colorTextSecondary: '#000000',
        colorTextTertiary: '#000000',
        colorBorder: '#006fff',
        borderRadius: 8,
        colorBgContainer: '#ffffff',
        colorBgElevated: '#ffffff',
        colorBgLayout: '#ffffff',
        colorPrimaryBg: '#006fff',
        backgroundColor: '#ffffff',
        colorError: '#ff4d4f',
        colorInfo: '#1890ff',
        colorLink: '#1890ff',
        controlHeight: 38,
    },

    darkAlgorithm: {
        colorPrimary: '#006fff',
        colorText: '#ffffff',
        colorTextQuaternary: '#ffffff',
        colorTextSecondary: '#ffffff',
        colorTextTertiary: '#ffffff',
        colorBorder: '#006fff',
        borderRadius: 8,
        colorBgContainer: '#000000',
        colorBgElevated: '#1f1f1f',
        colorBgLayout: '#1f1f1f',
        colorPrimaryBg: '#006fff',
        backgroundColor: '#000000',
        colorError: '#ff4d4f',
        colorInfo: '#1890ff',
        colorLink: '#1890ff',
        controlHeight: 38,
    }
}